#define IN_POSITION_LOCATION 0
#define IN_NORMAL_LOCATION 1
#define IN_MATERIAL_REF_LOCATION 2

#define TRANSFORMS_UBO_BINDING_INDEX 0
#define LIGHT_CONFIG_UBO_BINDING_INDEX 1
#define MATERIAL_CONFIG_UBO_BINDING_INDEX 2
